Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,10 +19,10 @@ jobs:
       PATH: $HOME/depot_tools:$PATH
     steps:
     - name: Check tar availability
-      run: which tar || echo "tar not found"
+      run: command -v tar || echo "tar not found"
 
     - name: Install tar
-      run: apt-get update && apt-get install -y tar
+      run: apt update && apt install -y tar
 
     - name: Checkout code
       uses: actions/checkout@v3
@@ -49,23 +49,23 @@ jobs:
     - name: Download depot_tools
       run: |
         git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ~/depot_tools
-        echo "export PATH=$HOME/depot_tools:$PATH" >> $GITHUB_ENV
-        echo "export PATH=$HOME/depot_tools:$PATH" >> ~/.bashrc
-        source ~/.bashrc
+        echo "$HOME/depot_tools" >> $GITHUB_PATH
 
     - name: Configure gclient
       run: |
         cat <<EOT > ~/.gclient
-        solutions = [
-          {
-            "name": "src",
-            "url": "https://chromium.googlesource.com/chromium/src.git",
-            "deps_file": "DEPS",
-            "managed": False,
-            "custom_deps": {}
-          }
-        ]
-        custom_vars = {}
+        {
+          "solutions": [
+            {
+              "name": "src",
+              "url": "https://chromium.googlesource.com/chromium/src.git",
+              "deps_file": "DEPS",
+              "managed": false,
+              "custom_deps": {}
+            }
+          ],
+          "custom_vars": {}
+        }
         EOT
 
     - name: Sync Chromium Source
